GROUP=io.github.zj565061763.android
POM_ARTIFACT_ID=compose-camera
VERSION_NAME=1.1.1

POM_NAME=compose-camera
POM_DESCRIPTION=Compose camera library.
POM_INCEPTION_YEAR=2026

POM_URL=https://github.com/zj565061763/compose-camera/
POM_SCM_URL=https://github.com/zj565061763/compose-camera/
POM_SCM_CONNECTION=scm:git:git://github.com/zj565061763/compose-camera.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/zj565061763/compose-camera.git

POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/license/mit
POM_LICENSE_DIST=repo

POM_DEVELOPER_ID=zj565061763
POM_DEVELOPER_NAME=zhengjun
POM_DEVELOPER_URL=https://github.com/zj565061763/

SONATYPE_HOST=CENTRAL_PORTAL
RELEASE_SIGNING_ENABLED=true
SONATYPE_AUTOMATIC_RELEASE=false